---
title: "Linear Model With Prediction"
author: "Connor Rice"
output: 
  html_document:
    number_sections: false
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"    
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(knitr)
require(foreign)
install.packages("ggplot2")
require(ggplot2)

mydata <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)

```

```{r}
model1 <- lm(SIMS~ARM,data=mydata)
plot(SIMS~ARM,data=mydata)
abline(model1)
specificdata1 <- data.frame(GRIP = 94, ARM = 88)
predict(model1, specificdata1, interval="confidence")
```

```{r}
model2 <- lm(SIMS~GRIP,data=mydata)
plot(SIMS~GRIP,data=mydata)
abline(model2)
specificdata2 <- data.frame(GRIP = 94, ARM = 88)
predict(model2, specificdata2, interval="confidence")
```

```{r}
model3 <- lm(SIMS~ARM + GRIP,data=mydata)
avPlots(model3)
abline(model3)
specificdata3 <- data.frame(GRIP = 94, ARM = 88)
predict(model3, specificdata3, interval="confidence")
```


```{r}
anova(model1,model3)
```
